# You should have a file like this (without the template extension) in your /config folder.
# It must not be checked into source control.

# Generate a secret token with the `rake secret` command
SECRET_TOKEN: CLASSIFIED

# Create your twitter app at https://dev.twitter.com/apps
TWITTER_CONSUMER_KEY: CLASSIFIED
TWITTER_CONSUMER_SECRET: CLASSIFIED
TWITTER_ACCESS_TOKEN: CLASSIFIED
TWITTER_ACCESS_SECRET: CLASSIFIED
